export const serviceGroups = ['All services', 'Maintenance', 'Diagnostics & electrical', 'Brakes & handling', 'Engine & drivetrain', 'Diesel & fleet'] as const;
const rows = [
 ['abs','ABS','Brakes & handling','Anti-lock braking system inspection and repair.','ABS warning lights, unusual pulsing, or changes in braking performance.'],
 ['ac-repair','AC Repair','Maintenance','Air-conditioning diagnosis and repair.','Warm air, weak airflow, or a system that no longer cools consistently.'],
 ['adas','ADAS','Diagnostics & electrical','Calibration and repair for modern driver-assistance systems.','Lane-assist, adaptive-cruise, or collision-avoidance system alerts.'],
 ['alternator-repair','Alternator Repair','Diagnostics & electrical','Testing and repair of the charging system.','Dimming lights, repeated battery problems, or a charging warning.'],
 ['engine-cooling','Engine Cooling','Engine & drivetrain','Radiator, water-pump, thermostat, and cooling-hose service.','Overheating, coolant loss, or temperature changes.'],
 ['electrical-repair','Electrical Repair','Diagnostics & electrical','Diagnosis of electrical faults, circuits, fuses, and sensors.','Intermittent electrical problems or accessories that stop working.'],
 ['auto-repair','Auto Repair','Maintenance','General automotive repair and troubleshooting.','A new noise, an unfamiliar vibration, or a change in how your vehicle drives.'],
 ['battery-installation','Battery Installation','Diagnostics & electrical','Battery testing, replacement, and installation.','Slow cranking, a no-start condition, or recurring battery trouble.'],
 ['brake-repair','Brake Repair','Brakes & handling','Inspection and repair of pads, rotors, calipers, and hydraulic components.','Squeaking, grinding, vibration, or a change in pedal feel.'],
 ['heater-repair','Heater Repair','Maintenance','Heating-system diagnosis and repair.','Little or no cabin heat, especially as the weather turns colder.'],
 ['catalytic-converter','Catalytic Converter','Engine & drivetrain','Inspection and replacement of catalytic converters.','Emission-related faults or a warning light that needs diagnosis.'],
 ['check-engine-light','Check Engine Light','Diagnostics & electrical','Testing to identify the cause of your engine warning light.','A dashboard alert, rough running, or reduced performance.'],
 ['computer-programming','Computer Programming','Diagnostics & electrical','Programming support for vehicle computer systems and electronic modules.','A module replacement or a vehicle-system issue requiring programming.'],
 ['cummins','Cummins','Diesel & fleet','Service for Cummins-powered trucks, including 5.9L and 6.7L engines.','Turbo, fuel-system, or drivability concerns in your Ram truck.'],
 ['diagnostics','Diagnostics','Diagnostics & electrical','Detailed vehicle testing backed by clear digital inspection information.','Warning lights, unusual sounds, or an issue that keeps returning.'],
 ['diesel-repair','Diesel Repair','Diesel & fleet','Light- and medium-duty diesel service for Cummins, Duramax, and Power Stroke.','Diesel engine, fuel-system, turbo, or emissions-system concerns.'],
 ['drivetrain-and-differential','Drivetrain & Differential','Engine & drivetrain','Driveshaft, axle, and differential repairs.','Driveline vibration, unusual noises, or problems transferring power.'],
 ['duramax','Duramax','Diesel & fleet','GM diesel diagnostics, fuel-system service, and emissions repairs.','Performance issues or warning lights on a Duramax-powered truck.'],
 ['engine-repair','Engine Repair','Engine & drivetrain','Engine repairs from gaskets to timing components.','Oil consumption, unfamiliar engine noises, or loss of power.'],
 ['exhaust-system','Exhaust System','Engine & drivetrain','Repair of exhaust leaks, hangers, and mufflers.','A louder exhaust, rattling, or an exhaust-system concern.'],
 ['factory-scheduled-maintenance','Factory-Scheduled Maintenance','Maintenance','Maintenance aligned with your vehicle manufacturer’s schedule.','A scheduled service milestone or an overdue maintenance item.'],
 ['fleet-services','Fleet Services','Diesel & fleet','Maintenance and repair support for local business vehicles.','A fleet that needs consistent scheduling and dependable upkeep.'],
 ['fuel-injector-service','Fuel Injector Service','Engine & drivetrain','Fuel injector cleaning and replacement.','Uneven acceleration, rough operation, or changes in fuel economy.'],
 ['hybrid-repair','Hybrid Repair','Diagnostics & electrical','Specialized hybrid diagnostics and repair, including battery and braking systems.','Hybrid-system alerts or a change in efficiency or performance.'],
 ['oil-changes','Oil Changes','Maintenance','Engine oil and filter service.','Your next oil-service interval or questions about the correct oil.'],
 ['power-stroke','Power Stroke','Diesel & fleet','Ford diesel service covering turbos, EGR, injectors, and DPF systems.','Drivability or emissions concerns with your Power Stroke engine.'],
 ['preventative-maintenance','Preventative Maintenance','Maintenance','Routine care for fluids, belts, brakes, and filters.','A vehicle you want to keep dependable through regular care.'],
 ['shocks-and-struts','Shocks & Struts','Brakes & handling','Inspection and replacement of worn ride-control components.','A bouncy ride, rough handling, or reduced stability.'],
 ['starter','Starter','Diagnostics & electrical','Starter testing and replacement.','A vehicle that will not crank or starts inconsistently.'],
 ['steering-repair','Steering Repair','Brakes & handling','Repair of power-steering pumps, racks, and tie rods.','Unusual steering effort, play, or handling concerns.'],
 ['suspension-repair','Suspension Repair','Brakes & handling','Suspension service for bushings, ball joints, shocks, and struts.','Clunks, uneven ride quality, or reduced control.'],
 ['tpms','TPMS','Diagnostics & electrical','Tire-pressure sensor testing, replacement, and programming.','A tire-pressure warning that needs investigation.'],
 ['transmission-repair','Transmission Repair','Engine & drivetrain','Service and repair for automatic, manual, and CVT transmissions.','Leaks, shifting changes, slipping, or clutch concerns.'],
 ['wheel-alignment','Wheel Alignment','Brakes & handling','Alignment service for consistent tracking and tire wear.','Drifting, uneven tire wear, or a steering wheel that sits off-center.'],
] as const;
export const serviceCatalog = rows.map(([slug,name,group,description,symptoms]) => ({slug,name,group,description,symptoms,image:group === 'Maintenance' ? '/carrolls-exterior-night.png' : group === 'Brakes & handling' ? '/carrolls-yellow-racecar.png' : group === 'Diagnostics & electrical' ? '/carrolls-black-racecar.png' : group === 'Diesel & fleet' ? '/carrolls-blue-racecar.png' : '/carrolls-family-racecar.png'}));
export const homeServiceSlugs: Record<string,string> = { diagnostics:'diagnostics', diesel:'diesel-repair', brakes:'brake-repair', maintenance:'preventative-maintenance', electrical:'electrical-repair', fleet:'fleet-services' };
export const articles = [
 {slug:'is-your-battery-on-its-last-charge',title:'Is your battery on its last charge?',category:'Electrical',date:'2026-01-25',dateLabel:'January 25, 2026',image:'/carrolls-exterior-night.png',intro:'A slow start is easy to put off—until the morning your vehicle will not start at all.',sections:[['Notice what has changed','Tell your technician about slower cranking, repeated jump starts, or a charging light. Those clues help distinguish a battery concern from a starter or charging-system fault.'],['Test before replacing','A battery is only one part of the starting system. Carroll’s can check the battery and investigate the cause of a recurring problem before recommending a repair.'],['Plan your next visit','Bring details about when the issue happens, recent work, and how often the vehicle is driven. A clear description helps the garage start in the right place.']],service:'battery-installation'},
 {slug:'dont-ignore-these-warning-signs-from-your-brakes',title:'Don’t ignore these warning signs from your brakes',category:'Brakes & safety',date:'2026-01-25',dateLabel:'January 25, 2026',image:'/carrolls-yellow-racecar.png',intro:'A new sound or change in pedal feel deserves attention. Your braking system should feel predictable.',sections:[['Listen to the change','Squeaking, grinding, or vibration can have different causes. Note when it happens—at low speed, under braking, or after the vehicle has been parked.'],['Get the complete system inspected','Pads and rotors are part of a larger system. An inspection can also identify concerns with calipers, hydraulic components, or ABS.'],['Ask for a clear explanation','Review the findings and estimate with the garage before repairs begin. If braking ability changes significantly, stop driving safely and arrange assistance.']],service:'brake-repair'},
 {slug:'why-regular-oil-changes-keep-your-engine-healthy',title:'Why regular oil changes keep your engine healthy',category:'Maintenance',date:'2026-01-22',dateLabel:'January 22, 2026',image:'/carrolls-family-owned.png',intro:'Regular oil service is a small part of vehicle ownership that belongs on a reliable schedule.',sections:[['Follow your vehicle’s schedule','Oil requirements vary by engine and use. Your owner’s manual and service history are the starting point for deciding when service is due.'],['Pay attention between services','Mention leaks, oil consumption, or dashboard warnings to the garage. An oil change does not replace diagnosis of an underlying engine problem.'],['Keep a service record','Recording maintenance helps you plan future visits and track changes over time. Carroll’s can help you work through scheduled and preventative maintenance.']],service:'oil-changes'},
];
export const areas = ['Sumner','Bonney Lake','Lake Tapps','Buckley','Tehaleh','Alderton','Dieringer','Puyallup','Auburn','Prairie Ridge','Ponderosa Estates','Benroy'];
export const testimonials = [
 {name:'John S.',quote:'Carroll’s Garage has always provided honest, reliable service. They explain exactly what’s needed, and I never feel pressured. Quick, efficient, and trustworthy!'},
 {name:'Amanda T.',quote:'Carroll’s Garage has taken care of my car for years. They always explain what’s needed, never push unnecessary repairs, and get me back on the road quickly.'},
 {name:'Emily T.',quote:'Excellent service from Carroll’s Garage. They’re honest, professional, and always get my car back in top shape. I highly recommend them to anyone'},
];
