"use client";
import {useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {serviceCatalog,serviceGroups,articles} from './content';
import {catalog,money} from '../shop/catalog';
export function ServiceDirectory(){const [query,setQuery]=useState('');const [group,setGroup]=useState('All services');const filtered=serviceCatalog.filter(s=>(group==='All services'||s.group===group)&&(s.name+' '+s.description).toLowerCase().includes(query.trim().toLowerCase()));return <section className="interior-section"><div className="directory-controls"><label>Find your service<input type="search" placeholder="Search brakes, diesel, oil…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Service category<select value={group} onChange={e=>setGroup(e.target.value)}>{serviceGroups.map(g=><option key={g}>{g}</option>)}</select></label><span aria-live="polite">{filtered.length} services</span>{(query || group!=='All services')&&<button type="button" className="directory-reset" onClick={()=>{setQuery('');setGroup('All services');}}>Reset filters ×</button>}</div><div className="service-directory">{filtered.map((s,i)=><Link href={`/services/${s.slug}`} key={s.slug}><span>{String(i+1).padStart(2,'0')} / {s.group}</span><h2>{s.name}</h2><p>{s.description}</p><b>Explore service</b></Link>)}</div>{!filtered.length&&<p className="empty-directory">No matching services. Try another term or <button onClick={()=>{setQuery('');setGroup('All services');}}>clear the filters</button>.</p>}</section>;}
export function ShopDirectory(){const [group,setGroup]=useState('all');const [sort,setSort]=useState('featured');const items=catalog.filter(p=>group==='all'||p.group===group).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0);return <section className="interior-section"><div className="directory-controls"><label>Collection<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">All merchandise</option><option value="tees">Tees</option><option value="hoodies">Hoodies</option><option value="headwear">Headwear</option><option value="goods">Garage goods</option></select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label><span aria-live="polite">{items.length} pieces</span></div><div className="store-directory">{items.map(p=><Link href={`/products/${p.slug}`} key={p.slug}><div><Image src={p.image} width={600} height={600} sizes="(max-width: 600px) 50vw, 25vw" alt={p.name}/><span>Shop now ↗</span></div><p>{p.category}</p><h2>{p.name}</h2><strong>{money(p.price)}</strong></Link>)}</div></section>;}

export function BlogDirectory() {
  const [query,setQuery] = useState('');
  const [category,setCategory] = useState('All posts');
  const categories = ['All posts', ...new Set(articles.map(article=>article.category))];
  const posts = articles.filter(article=>(category==='All posts'||article.category===category)&&(article.title+' '+article.intro).toLowerCase().includes(query.trim().toLowerCase()));
  const reset = () => {setQuery('');setCategory('All posts');};
  return <section className="interior-section">
    <div className="directory-controls"><label>Find car care advice<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search battery, brakes, oil…" /></label>{(query||category!=='All posts')&&<button type="button" className="directory-reset" onClick={reset}>Reset filters ×</button>}</div>
    <div className="blog-topic-filters" role="group" aria-label="Filter blog by topic">{categories.map(topic=><button key={topic} type="button" aria-pressed={category===topic} onClick={event=>{setCategory(topic);event.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'});}}>{topic}</button>)}</div>
    <p className="directory-results" role="status">{posts.length} {posts.length===1?'article':'articles'}{category!=='All posts'?' · '+category:''}</p>
    <div className="journal-directory">{posts.map(article=><Link href={`/blog/${article.slug}`} key={article.slug}><Image src={article.image} width={900} height={600} sizes="(max-width: 700px) 100vw, 33vw" alt={article.category}/><div><p className="shop-kicker">{article.category}</p><time dateTime={article.date}>{article.dateLabel}</time><h2>{article.title}</h2><p>{article.intro}</p><b>Read the article ↗</b></div></Link>)}</div>
    {!posts.length&&<div className="empty-directory"><p>No articles match your search. Try a different term or explore all car care topics.</p><button type="button" onClick={reset}>Show all articles →</button></div>}
  </section>;
}
