import {notFound} from 'next/navigation';
import Link from 'next/link';
import type {Metadata} from 'next';
import {serviceCatalog} from '../../site/content';
import {SiteFrame,PageIntro} from '../../site/frame';
import {MobileRail,MobileReveal} from '../../site/mobile-content';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const s=serviceCatalog.find(s=>s.slug===slug);return {title:s?`${s.name} in Sumner | Carroll’s Garage`:'Service not found',description:s?.description,openGraph:{images:[]},twitter:{images:[]}};}
export default async function ServicePage({params}:Props){const {slug}=await params;const service=serviceCatalog.find(s=>s.slug===slug);if(!service)notFound();return <SiteFrame><PageIntro label={service.name} title={service.name+'. Straight answers included.'} copy={service.description} image={service.image}/><section className="service-detail-layout"><article><p className="shop-kicker">{service.group}</p><h2>Know what to look for.</h2><p>{service.symptoms}</p><MobileReveal label="What to tell your technician"><p>Tell us when you first noticed the issue, when it happens, and any recent service work. We’ll investigate the concern and explain the findings before recommending the next step.</p></MobileReveal><h2>What happens at the shop?</h2><ol className="service-steps"><li><details name="service-steps"><summary><b>Discuss the concern</b></summary><p>We start with your vehicle, its history, and what you are experiencing.</p></details></li><li><details name="service-steps"><summary><b>Inspect and explain</b></summary><p>Our technicians investigate and share clear inspection information.</p></details></li><li><details name="service-steps"><summary><b>Review the estimate</b></summary><p>You approve the recommended work before repairs begin.</p></details></li><li><details name="service-steps"><summary><b>Repair and verify</b></summary><p>Approved work is completed and checked before pickup.</p></details></li></ol><Link className="interior-link" href="/services">Browse all services</Link></article><aside><p className="shop-kicker">BOOK {service.name}</p><h2>Let’s take a look.</h2><p>Get in touch to arrange a visit and discuss your vehicle.</p><Link className="shop-primary" href={`/appointment?service=${service.slug}`}>Request this service</Link><a className="service-phone" href="tel:+12538632524">(253) 863-2524</a><hr/><p>ASE-certified technicians<br/>Digital inspection information<br/>1-year / 12,000-mile repair warranty</p><Link href="/financing">Explore financing</Link></aside></section><section className="interior-section"><p className="shop-kicker">RELATED SERVICES</p><MobileRail className="related-services" label="related service">{serviceCatalog.filter(s=>s.group===service.group&&s.slug!==service.slug).slice(0,3).map(s=><Link href={`/services/${s.slug}`} key={s.slug}><h2>{s.name}</h2><p>{s.description}</p><b>Explore</b></Link>)}</MobileRail></section></SiteFrame>;}
